### ISSUE TITLE
Punto 3 (2da Entrega )

### ISSUE THREAD

**Issue by Nacufala** [FrancoQuiroga04/Grupo2Paradigmas#46]
cuantosMiranLaSerie/2 falta generar para que sea inservible

**Comment by Nacufala** [comment]
cuantosHablanDeLaSerie/2 NO hay que usar **2** findall 
solo se cuenta conversaciones no cantidad de personas "cantidad de conversaciones de la misma"

**Comment by sanuzzi** [comment]
Cierren este issue (no tengo permisos para hacerlo yo)
